[package]
name = "rust_genos"
version = "0.1.0"
authors = ["Cypooos <60020572+Cypooos@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
x86_64 = "0.12.1"
spin = "0.5"
lazy_static = { version = "1", features = ["spin_no_std"] }
volatile = "0.2"
bootloader = "0.9.8"


# the profile used for `cargo build`
[profile.dev]
# the profile used for `cargo build --release`
[profile.release]
panic = "abort"

[features]
# The reason we do this is because I don't get cfg(test)
test = []

[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04"]
test-success-exit-code = 33         # (0x10 << 1) | 1
